### ISSUE TITLE
Can't get it to work with aviutl

### ISSUE THREAD

**Issue by archienz** [MaverickTse/aviutl-waifu2x-gl#1]
Hey Maverick,

I've tried to add this keeping the base structure to the aviutl path, however once i have started up aviutl, it won't show up on the list or dropdown menus.

Any ideas?

**Comment by archienz** [comment]
Oh c'mon man, i would answer your questions if i worked on parts of it, least you could do!

I actually managed to get a GPU version and CPU version working, but this one won't work. I would love to try it out.

**Comment by MaverickTse** [comment]
Mind you attitude man, that's not the way you call for help.
The released file here still works on my machine
![waifu2x_working](https://cloud.githubusercontent.com/assets/10569988/10408271/9655a7fe-6f2b-11e5-905c-7e86baecfc2a.png)

(Win7 64bit, Nvidia GTX970, Intel 5820k)

Show me the following or I'd have no idea what's wrong with your machine:
1. AviUtl base folder structure (print screen/dir/tree... whatever)
2. OS
3. Graphics chipset
4. a screen capture of your Filter Menu

**Comment by archienz** [comment]
Curious, should i keep folder structure as in zip and just extract to aviutl folder, you have an awesome program btw, i prefer it over many others like xvid4psp etc, my only gripe is slow integration of things like mkv container and mp4 etc.

Ok

1.Will attach here soon(no access right now)
2. Windows 7 (64) SP1 etc.
3. http://www.gigabyte.com.au/products/product-page.aspx?pid=4345#ov (amd 7750 2gb) and 6950 http://www.newegg.com/Product/Product.aspx?Item=N82E16814102945 2gb
4. Will attach here soon(no access right now)

**Comment by MaverickTse** [comment]
Just retain the archive's folder structure. That means you are going to add 2 new folders in /aviutl/,
and a bunch of DLL and .auf side-by-side with aviutl.exe

The Sapphire should have no problem running the code (if connecting to monitor).

CPU.... you are killing it

xvid4psp... it is a transcoder... while AviUtl is primarily an Editor, so use the right tool.

The faster waifu2x implementation right now all use CUDA (and Intel CPU), and this OCL wrapper is no match with CUDA.
**I'd suggest you to try this also:**
[https://github.com/YSRKEN/aviutl-waifu2x-w2xc]
which can utilize CUDA, OCL, and various SIMD

**Comment by MaverickTse** [comment]
If there are no more response by weekend, I'm closing this issue.
